name: CI
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit
        uses: EndBug/add-and-commit@v8
        with:
          new_branch: compiled
          add: '[".", "assets/*bundle* --force"]'
          push: false

      - name: Git
        run: | 
          git branch
          git remote -v

      - name: Pull
        run: git pull origin compiled --rebase -X ours

      # - name: Git
      #   # run: |
      #   #   git log --oneline -n 1
      #   #   git pull origin compiled --no-rebase --allow-unrelated-histories -X ours
      #   #   git push origin compiled --set-upstream
      #   # run: |
      #   #   git pull origin compiled --rebase -X
      #   run: |
      #     git log --oneline -n 5
      #     git merge compiled -X theirs

      - name: Push
        run: |
          git push origin compiled --set-upstream


  
